// Copyright (c) 2026 Sachu James. SPDX-License-Identifier: MIT.
//
// QueueTracker: queue-position tracking for designated orders (SPEC.md
// section 8). Answers: where is a designated order in its price-level
// FIFO queue, how much quantity is ahead of it, and what is its
// lifecycle state.
//
// Design:
//   * The tracker is a passive observer. It never mutates the book and
//     never performs matching. It reads queue state exclusively through
//     the OrderBook's public query API (find, ordersAtLevel, contains).
//   * "Designated" orders are explicitly registered via designate().
//     Tracking is opt-in per order id, so the component stays cheap when
//     only a few orders matter (e.g. simulated orders under study).
//   * Lifecycle (resting / filled / cancelled) is derived from the
//     validated event stream and the Fill records the caller feeds in via
//     onEvent()/onFills(). Queue advancement itself is never estimated:
//     it is recomputed from the live book on every query, so it always
//     reflects actual inserts, cancels, modifies, and executions.
//   * Position semantics follow SPEC.md 8.1 exactly: 1-based FIFO index
//     by arrivalSeq within the price level; quantity ahead is the sum of
//     remaining quantities earlier in the same level's queue. Order ids
//     never determine priority.

#pragma once

#include "tickforge/book/order_book.hpp"
#include "tickforge/event/event.hpp"
#include "tickforge/matching/fill.hpp"

#include <cstddef>
#include <cstdint>
#include <optional>
#include <span>
#include <unordered_map>
#include <unordered_set>
#include <vector>

namespace tickforge {

class QueueTracker {
public:
  QueueTracker() = default;

  // Designate an order id for tracking. Idempotent. Should be called
  // before the order's NewOrder event for full lifecycle fidelity, but
  // position queries also work for orders designated late (they read the
  // live book).
  void designate(OrderId id);

  // Stop tracking an order id. Idempotent.
  void release(OrderId id);

  [[nodiscard]] bool isTracked(OrderId id) const;

  // Observe a validated event, in stream order. Maintains lifecycle
  // bookkeeping for designated ids (new / cancel / modify). Safe to call
  // for non-designated ids (ignored).
  void onEvent(const Event& event);

  // Observe the fills generated by the most recent event, in order.
  // Maintains executed-quantity bookkeeping for designated ids.
  void onFills(std::span<const Fill> fills);

  // Snapshot of a designated order's queue state. Empty when the id is
  // not tracked or not currently resting in the book.
  struct QueuePosition {
    Side side;
    Price price;
    std::size_t rank;           // 1-based index in the level's FIFO queue
    Quantity quantityAhead;     // lots resting ahead in the same level
    Quantity quantityRemaining; // the order's own remaining lots
  };
  [[nodiscard]] std::optional<QueuePosition> queuePosition(const OrderBook& book,
                                                           OrderId id) const;

  // Lifecycle of a designated order id.
  enum class Lifecycle : std::uint8_t {
    Unknown,   // not tracked, or tracked but never observed
    Resting,   // currently in the book
    Filled,    // left the book via execution
    Cancelled, // left the book via CancelOrder
  };
  [[nodiscard]] Lifecycle lifecycle(const OrderBook& book, OrderId id) const;

private:
  struct TrackedState {
    Quantity originalQuantity{0};
    Price currentPrice{0};
    std::int64_t filledLots{0};
    bool newSeen{false};
    bool cancelSeen{false};
  };

  std::unordered_set<OrderId> designated_;
  std::unordered_map<OrderId, TrackedState> states_;

  [[nodiscard]] TrackedState& stateFor(OrderId id);
  void resetForNew(OrderId id, Quantity quantity);
};

} // namespace tickforge
