// Copyright (c) 2026 Sachu James. SPDX-License-Identifier: MIT.
//
// Matching engine (SPEC.md sections 5.4 and 6): deterministic price-time
// priority matching on top of the MBO order book.
//
// Responsibility split:
//   * Replay engine: event ordering, validation, dispatch. Knows nothing
//     about matching.
//   * MatchingEngine: crossing detection, price-time priority selection,
//     fill generation, residual handling. Operates on the OrderBook only
//     through its public semantic API; never touches book containers.
//   * OrderBook: resting-order state. Performs no matching itself.
//
// Semantics (derived from SPEC.md):
//   * Only NewOrder events can be aggressors. Every NewOrder is a limit
//     order (SPEC.md 2.3).
//   * A bid crosses when bid price >= best ask; an ask crosses when ask
//     price <= best bid. Equality crosses.
//   * Execution price is the resting order's price.
//   * Fills are generated best-price-first, then FIFO (arrivalSeq) within
//     a price. An aggressor never consumes beyond its limit price.
//   * A partially filled resting order keeps its queue position and
//     arrivalSeq with reduced quantity.
//   * Unfilled residual quantity rests in the book (SPEC.md 7: an
//     incompletely matched incoming order's remainder rests). There is no
//     IOC/FOK: the flags field is reserved and ignored.
//   * A ModifyOrder whose price change makes it cross is treated as
//     cancel/replace (SPEC.md 5.5) and matches as an aggressor with the
//     modify event's timestamp/seq. A modify that does not newly cross is
//     handled by the book's Day 03 semantics.
//   * Self-trade by order id is impossible: a NewOrder with a live id is
//     rejected as a duplicate (SPEC.md 5.1), so an aggressor never meets
//     its own id in the book. No participant fields exist; self-trade
//     prevention beyond this is out of scope.

#pragma once

#include "tickforge/book/order_book.hpp"
#include "tickforge/event/event.hpp"
#include "tickforge/matching/fill.hpp"
#include "tickforge/replay/event_processor.hpp"

#include <vector>

namespace tickforge {

class MatchingEngine : public EventProcessor {
public:
  explicit MatchingEngine(OrderBook& book);

  // Applies one validated event, performing matching when the event is
  // aggressive. Returns false when the event is rejected: cancel/modify
  // of a non-resting order, or a new order whose id is already live.
  // Fills generated by this event are available via fills() until the
  // next onEvent call.
  bool onEvent(const Event& event) override;

  // Fills from the most recent onEvent call, in deterministic order:
  // best eligible price first, then FIFO within a price. Empty when the
  // last event generated no fills.
  [[nodiscard]] const std::vector<Fill>& fills() const noexcept;

  [[nodiscard]] OrderBook& book() noexcept;

private:
  OrderBook& book_;
  std::vector<Fill> fills_;

  bool processNewOrder(const Event& event);
  bool processModify(const Event& event);

  // Matches quantity of an aggressive order against the book, recording
  // fills. Any unfilled residual rests in the book with arrivalSeq.
  void matchAggressor(OrderId aggressorId,
                      Side side,
                      Price limitPrice,
                      Quantity quantity,
                      Timestamp timestamp,
                      Sequence arrivalSeq);

  // Crossing test for one resting price level.
  static bool crosses(Side aggressorSide, Price limitPrice, Price restingPrice) noexcept;
};

} // namespace tickforge
